FROM ubuntu:22.04

LABEL maintainer=kmaddela@nyit.edu

# Install Python and other dependencies as root
USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# Set working directory
WORKDIR /app

# Copy the application code
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create a non-root user and switch to it
RUN useradd -m usr
USER usr

# Expose the port FastAPI will run on
EXPOSE 8001

# Run the FastAPI application using Uvicorn
ENTRYPOINT ["fastapi", "dev", "endpoint.py"]